**Theoretical Questions:**

In [ ]:
#Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

"""Purpose of NumPy in Scientific Computing and Data Analysis
NumPy (Numerical Python) is a powerful library designed to efficiently handle numerical data and perform mathematical operations in Python.
It is particularly well-suited for scientific computing, data analysis, and engineering applications.
NumPy provides support for arrays, matrices, and a wide range of numerical operations that make it an essential tool for handling large datasets, complex mathematical computations, and multidimensional data structures.

The key purpose of NumPy in scientific computing and data analysis is to provide:

Efficient Numerical Data Storage: NumPy allows the storage of large datasets in a highly efficient format, reducing memory consumption and improving access speed.

Vectorized Operations: NumPy enables element-wise operations on entire arrays or matrices, avoiding the need for slow Python loops and making code cleaner and faster.

Advanced Mathematical Functions: The library offers a wide array of mathematical, statistical, and algebraic functions optimized for arrays.

Multidimensional Arrays: NumPy supports arrays of any number of dimensions, enabling complex data structures like matrices, tensors, and grids, which are fundamental for many scientific applications.


Advantages of NumPy in Scientific Computing and Data Analysis
Performance and Efficiency:

Speed: NumPy is implemented in C, and operations on NumPy arrays are performed in compiled code instead of interpreted Python.
This makes NumPy much faster than native Python lists for numerical computations, especially for large datasets.
Memory Efficiency: NumPy arrays consume less memory because they store data in contiguous memory blocks and have a fixed data type.
This contrasts with Python lists, which are more flexible but also more memory-intensive.
Vectorized Operations:

NumPy supports vectorized operations, meaning you can perform mathematical operations directly on arrays without having to loop over individual elements.
This leads to cleaner, more concise, and significantly faster code."""

#example:

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b

"""Multidimensional Arrays:

NumPy allows the creation of multidimensional arrays (like matrices or higher-dimensional tensors), which is crucial in scientific and engineering problems.
This capability is foundational for many machine learning models, simulations, and data manipulations."""

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

"""Convenient Mathematical Operations:

NumPy provides a wide range of mathematical functions (e.g., linear algebra, statistics, Fourier transforms, etc.) that operate directly on arrays, such as:
Element-wise operations: addition, multiplication, exponentiation
Linear algebra operations: dot products, matrix multiplication, eigenvalues
Statistical functions: mean, standard deviation, correlation
Random number generation: generating random numbers for simulations, random sampling, etc."""

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)  # Calculate mean
std_dev = np.std(arr)      # Calculate standard deviation

"""Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes.
This feature automatically adjusts arrays of smaller sizes to match larger ones, eliminating the need for explicit looping or reshaping.
Broadcasting is a powerful feature for efficient handling of arithmetic between arrays with different shapes."""
a = np.array([1, 2, 3])
b = np.array([10])
c = a + b  # Broadcasting allows the addition of a scalar to an array

"""How NumPy Enhances Python's Capabilities for Numerical Operations
Array Data Structure:

Native Python provides lists, but lists are slow and inefficient for numerical tasks.
NumPy enhances Python by introducing N-dimensional arrays (ndarray), which can store large datasets efficiently and support complex operations.

Optimized for Numerical Computations:

NumPy arrays are optimized for numerical operations, offering significant performance improvements over Python’s built-in list operations.
The functions in NumPy are implemented in C and are highly optimized for operations on arrays.

No Need for Explicit Loops:

With NumPy, you can perform complex operations on entire arrays or matrices without explicitly writing loops.
This improves both the readability and performance of the code.
Scientific Computing Libraries:

NumPy is the foundation of many popular scientific computing libraries like SciPy, Pandas, and SymPy.
By providing an efficient array object and mathematical functions, NumPy supports these libraries in carrying out tasks like optimization, integration, data manipulation, and statistical analysis."""



In [ ]:
#Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
""" - Both np.mean() and np.average() are functions in NumPy that are used to calculate the average (or central tendency) of a dataset, but they have some key differences in terms of flexibility and functionality.
Here’s a detailed comparison and when to use each function.
 - np.mean():
This function calculates the arithmetic mean of an array along a specified axis.
It’s the sum of all elements divided by the number of elements. It does not provide any additional options for weighting the data.
 - np.average():
This function also calculates the mean but provides more flexibility, as it allows you to compute the weighted average.
In addition to calculating the arithmetic mean, you can provide a set of weights for the data, making it useful when different values should contribute differently to the result.

Use Cases and Scenarios
Use np.mean() when:

You need to calculate the simple arithmetic mean of the dataset.
You do not need to apply any weighting to the values.
You are working with data where each value is equally important or represents the same magnitude.
Example: Calculating the average score of students where each student has the same weight:"""

scores = np.array([90, 80, 85, 92, 88])
mean_score = np.mean(scores)

"""Use np.average() when:

You need to compute a weighted average.
Different data points have different levels of importance or should contribute differently to the result.
Example: Calculating the weighted average score of students where different students' scores count more based on their number of hours studied:"""

scores = np.array([90, 80, 85, 92, 88])
hours_studied = np.array([10, 5, 8, 7, 6])  # Weights
weighted_avg_score = np.average(scores, weights=hours_studied)
weighted_avg_score



87.55555555555556

In [ ]:
#Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# - Reversing a 1D Array
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reversing the 1D array
reversed_arr = arr_1d[::-1]

#Reversing a 2D Array
"""For a 2D array, you can reverse the array along different axes: along rows (axis 0) or along columns (axis 1).

Method 1: Reversing along axis 0 (rows)
Reversing along axis 0 means reversing the order of the rows in the 2D array. This can be done using slicing or the flipud() function, which stands for "flip up-down."""

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along axis 0 (rows)
reversed_rows = arr_2d[::-1, :]

#OR
reversed_rows = np.flipud(arr_2d)


print("Original array:\n", arr_2d)
print("Reversed along rows (axis 0):\n", reversed_rows)

"""Reversing along axis 1 (columns)
Reversing along axis 1 means reversing the order of the columns. This can be done using slicing or the fliplr() function, which stands for "flip left-right."""


# Reversing along axis 1 (columns)
reversed_columns = arr_2d[:, ::-1]

print("Original array:\n", arr_2d)
print("Reversed along columns (axis 1):\n", reversed_columns)

#OR
reversed_columns = np.fliplr(arr_2d)



Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows (axis 0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along columns (axis 1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
#Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
#- can determine the data type of the elements in an array using the dtype attribute.
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Checking the data type of the array elements
print(arr.dtype)

"""
 importance of data types in memory management and performance

Memory Efficiency: Choosing an appropriate dtype ensures that memory is used efficiently, reducing unnecessary overhead and improving performance.

Performance: Smaller data types typically offer better performance for large datasets since they reduce memory access time and processing power needed for computations.

Avoiding Errors: Using an appropriate dtype helps prevent data overflows, underflows, or loss of precision.

Optimized Operations: NumPy’s functions are optimized for specific data types, so choosing the right dtype can lead to faster execution times in computational tasks.

Interoperability: The correct data type ensures that your data is compatible with other libraries and systems that expect specific formats."""

int64


In [ ]:
#Q5 - Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
"""An ndarray (short for n-dimensional array) is the central data structure in NumPy, a powerful Python library for numerical computing. It represents a multidimensional, homogeneous array, i.e., it can hold elements of the same data type and can have any number of dimensions (from 1D to nD).

An ndarray is more efficient than Python's standard list data structure because it is optimized for numerical operations. It is used to store and manipulate data in a variety of forms, including vectors, matrices, and higher-dimensional data structures.

 - Key Features of ndarrays:

 - Homogeneous Data Type:

All elements in an ndarray must be of the same data type, which allows for efficient storage and computation.
This contrasts with Python lists, which can store items of different types (e.g., integers, strings, etc.).

 - Multidimensional:

Ndarrays can represent data with one or more dimensions, making them suitable for various types of data (vectors, matrices, higher-dimensional arrays).
A 1D array is a vector, a 2D array is a matrix, and a 3D array could represent a set of matrices or multi-dimensional grids.

 - Fixed Size:

Once created, the size of an ndarray is fixed. This means you can't resize an ndarray after its creation like you can with Python lists (i.e., appending or removing elements in a list).
However, you can create a new ndarray with the desired size or use slicing to modify portions of an ndarray.

 - Efficient Memory Layout:

NumPy ndarrays are stored in contiguous blocks of memory, which ensures faster access and manipulation of elements compared to Python lists, which are stored as pointers to individual elements.
This allows for vectorized operations (operations on entire arrays without the need for explicit loops), which significantly enhances performance.

 - Broadcasting:

Ndarrays support broadcasting, a powerful feature that allows NumPy to perform element-wise operations on arrays of different shapes, as long as they are compatible according to certain rules. This eliminates the need for explicit looping and increases efficiency.


 - Differences Between ndarrays and Standard Python Lists

 - Homogeneity:

ndarrays: Elements must be of the same data type.
Python Lists: Can store elements of different data types (e.g., integers, strings, etc.).

 - Performance:

ndarrays: Operations on ndarrays are faster due to their contiguous memory layout and optimized C-based implementation.
Python Lists: Slower due to the overhead of storing references to objects in memory and the lack of efficient memory management.

 - Memory Efficiency:

ndarrays: Store data in a compact, fixed-size format.
Python Lists: Store data as references to objects, leading to higher memory overhead.

 - Functionality:

ndarrays: NumPy provides a wide range of mathematical, statistical, and logical operations that are fast and efficient.
Python Lists: Do not have built-in support for advanced mathematical operations or multi-dimensional data.

 - Mutability:

ndarrays: While the size of an ndarray is fixed upon creation, the data within it can be modified (mutability is allowed).
Python Lists: Lists are mutable and can have their size changed by appending, removing, or altering elements.

 - Shape and Dimensions:

ndarrays: Support multi-dimensional data (1D, 2D, 3D, etc.).
Python Lists: Can only hold one-dimensional data (although you can nest lists within lists to simulate higher dimensions, but this isn't as efficient or straightforward as ndarrays).

In [ ]:
#Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
"""In large-scale numerical operations, NumPy arrays offer substantial performance benefits over Python lists.

These benefits stem from their:

 - Memory efficiency, due to contiguous blocks of memory and fixed data types.
 - Speed, through optimized vectorized operations and low-level C-based implementations.
 - Parallelization and optimized algorithms for handling large datasets.

In contrast, Python lists are more general-purpose and less optimized for numerical computing, making them slower and more memory-inefficient for large-scale numerical tasks.
Therefore, for tasks involving significant amounts of data or requiring high computational performance (e.g., linear algebra, statistical analysis, machine learning), NumPy arrays are the clear choice."""

#Example: numpy in python
import numpy as np

# Create two large arrays
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized addition of arrays
result = a + b


#Example: Python list
# Create two large lists
a = [random.random() for _ in range(1000000)]
b = [random.random() for _ in range(1000000)]

# Manual addition using a loop
result = [a[i] + b[i] for i in range(len(a))]

In [ ]:
#Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
"""In NumPy, vstack() and hstack() are functions used to stack arrays along different axes, specifically for combining arrays vertically or horizontally.
Here's a comparison of the two functions, along with examples demonstrating their usage.

vstack() Function
Purpose: The vstack() function stacks arrays vertically (along rows). It combines arrays along the first axis (axis 0), meaning it appends the arrays one below the other.
Input Requirement: The arrays being stacked must have the same number of columns (i.e., the same shape along axis 1).
hstack() Function
Purpose: The hstack() function stacks arrays horizontally (along columns). It combines arrays along the second axis (axis 1), meaning it appends the arrays side by side.
Input Requirement: The arrays being stacked must have the same number of rows (i.e., the same shape along axis 0)."""

#Example 1: Using vstack()

import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack arrays vertically
result_vstack = np.vstack((arr1, arr2))

print("Result of vstack:")
print(result_vstack)

#Example 2: Using hstack()

# Stack arrays horizontally
result_hstack = np.hstack((arr1, arr2))

print("Result of hstack:")
print(result_hstack)

Result of vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Result of hstack:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Q8 - Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

"""fliplr():
Flips horizontally along the columns (axis 1).
Reverses the order of elements in each row.

flipud():
Flips vertically along the rows (axis 0).
Reverses the order of the rows.
These methods are particularly useful when performing transformations, image processing, or manipulating multidimensional data arrays."""

#Example 1: 1D Array

arr_1d = np.array([1, 2, 3, 4])

# Flip left to right
flipped_lr_1d = np.fliplr([arr_1d])

# Flip up to down
flipped_ud_1d = np.flipud([arr_1d])

print("Original 1D array:")
print(arr_1d)

print("Flipped left to right (fliplr):")
print(flipped_lr_1d)

print("Flipped up to down (flipud):")
print(flipped_ud_1d)

#Example 2: 3D Array (Higher-Dimensional Example)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flip left to right
flipped_lr_3d = np.fliplr(arr_3d)

# Flip up to down
flipped_ud_3d = np.flipud(arr_3d)

print("Original 3D array:")
print(arr_3d)

print("Flipped left to right (fliplr):")
print(flipped_lr_3d)

print("Flipped up to down (flipud):")
print(flipped_ud_3d)

Original 1D array:
[1 2 3 4]
Flipped left to right (fliplr):
[[4 3 2 1]]
Flipped up to down (flipud):
[[1 2 3 4]]
Original 3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Flipped left to right (fliplr):
[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
Flipped up to down (flipud):
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


In [ ]:
#Q9 - Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
""" - The array_split() method in NumPy is a powerful tool that allows you to split an array into multiple sub-arrays.
Unlike the basic split() method, which requires the array to be evenly divisible by the number of desired splits,
array_split() can handle cases where the array size is not perfectly divisible by the number of splits. This makes it more flexible and useful for handling uneven splits.

Syntax of array_split()"""

"""Example 1: Splitting an Array into Uneven Parts
Let's consider an array with 10 elements that we want to split into 3 parts."""


import numpy as np

# Create an array of 10 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split into 3 parts
split_arr = np.array_split(arr, 3)

print("Array split into 3 parts:")
for part in split_arr:
    print(part)


"""Example 2: Splitting Along Rows (2D Array)
Let's split a 2D array along the rows (axis 0) where the number of rows is not evenly divisible by the number of splits."""

# Create a 2D array with 6 rows and 4 columns
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]])

# Split into 4 parts along rows (axis 0)
split_arr_2d = np.array_split(arr_2d, 4, axis=0)

print("Array split along rows (axis 0):")
for part in split_arr_2d:
    print(part)

Array split into 3 parts:
[1 2 3 4]
[5 6 7]
[ 8  9 10]


In [ ]:
#Q10 -  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
"""Vectorization: The ability to apply operations across entire arrays without explicit loops, making array operations faster and more efficient.
NumPy internally uses optimized C code to handle these operations, which speeds up execution significantly.

Broadcasting: A mechanism that allows NumPy to perform operations between arrays of different shapes by automatically expanding the smaller array to match the larger array’s shape.
 This saves memory and reduces the need for redundant data replication.
Together, vectorization and broadcasting enable efficient, readable, and memory-efficient array operations in NumPy.
They help avoid the need for slow Python loops, make use of low-level optimizations, and allow operations on arrays of different shapes without explicitly reshaping or duplicating arrays."""

"""How Vectorization and Broadcasting Contribute to Efficient Array Operations

Avoiding Loops:

Vectorization allows you to perform operations on entire arrays without the need for explicit loops in Python.
This not only makes the code cleaner but also speeds up execution since NumPy leverages optimized C code under the hood.

Reduced Memory Usage:

Broadcasting allows NumPy to perform operations on arrays of different shapes without duplicating data.
This reduces the memory overhead, especially when dealing with large arrays.
Instead of creating intermediate large arrays to match shapes, broadcasting allows operations to be performed in-place without unnecessary data duplication.

Parallelism and Optimization:

NumPy internally optimizes operations for speed by taking advantage of low-level libraries like BLAS (Basic Linear Algebra Subprograms), which can perform operations in parallel on multiple CPU cores.
Both vectorization and broadcasting make use of this parallelism, resulting in significant performance improvements over plain Python loops.

Simplified Code:

Both vectorization and broadcasting lead to cleaner, more concise code.
Instead of manually iterating through arrays and performing operations element by element, you can express operations as single expressions that apply across entire arrays, improving readability."""


#Example of Vectorization:
#Without vectorization (using a loop):


import numpy as np

arr = np.array([1, 2, 3, 4])

# Adding 2 to each element (using loop)
result = []
for x in arr:
    result.append(x + 2)

print(result)

#With vectorization (NumPy's built-in operation):


arr = np.array([1, 2, 3, 4])

# Adding 2 to each element (vectorized operation)
result = arr + 2

print(result)


#Example of Broadcasting:
#Consider adding a 2D array and a 1D array:


import numpy as np

# 2D array (3x4)
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# 1D array (1x4)
arr_1d = np.array([1, 2, 3, 4])

# Adding the 1D array to the 2D array (broadcasting)
result = arr_2d + arr_1d

print(result)




[3, 4, 5, 6]
[3 4 5 6]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


**Practical Questions**

In [ ]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
arr1 = np.random.randint(1,101,(3,3))
print(arr1)

a = arr1.T
a

[[ 91  10  78]
 [100  79 100]
 [ 10  25  42]]


array([[ 91, 100,  10],
       [ 10,  79,  25],
       [ 78, 100,  42]])

In [ ]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
l = [1,2,3,4,5,6,7,8,9,10]
ar = np.array(l)
ar.ndim
ar1 = ar.reshape(2,5)
ar1
ar2 = ar.reshape(5,2)
ar2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
ar = np.random.rand(4,4)
ar
# Add a border of zeros around the array, resulting in a 6x6 array
array_with_border = np.pad(ar, pad_width=1, mode='constant', constant_values=0)

# Display the array with the border
print("Original 4x4 Array:")
print(ar)

print("\nArray with Border (6x6):")
print(array_with_border)

Original 4x4 Array:
[[0.64509172 0.04121659 0.63368678 0.62621798]
 [0.21888022 0.42869635 0.21747581 0.19815909]
 [0.4694586  0.47237313 0.39336142 0.82441617]
 [0.51255587 0.43033117 0.24297687 0.66343915]]

Array with Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.64509172 0.04121659 0.63368678 0.62621798 0.        ]
 [0.         0.21888022 0.42869635 0.21747581 0.19815909 0.        ]
 [0.         0.4694586  0.47237313 0.39336142 0.82441617 0.        ]
 [0.         0.51255587 0.43033117 0.24297687 0.66343915 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [2]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
a1 = np.random.randint(10,61,5)
a1

array([37, 18, 49, 25, 51])

In [10]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
import numpy as np
arr1 = np.array(['python', 'numpy', 'pandas'])
print("UpperCase = ", np.char.upper(arr1))
print("LowerCase = ", np.char.lower(arr1))
print("Title = ", np.char.title(arr1))
print("Capital = ", np.char.capitalize(arr1))


UpperCase =  ['PYTHON' 'NUMPY' 'PANDAS']
LowerCase =  ['python' 'numpy' 'pandas']
Title =  ['Python' 'Numpy' 'Pandas']
Capital =  ['Python' 'Numpy' 'Pandas']


In [11]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_arr = np.array([' '.join(word) for word in arr])

# Print the result
print(spaced_arr)

['p y t h o n' 'n u m p y' 'p a n d a s']


In [19]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
arr1 = np.random.randint(1,10,(5,5))
arr2 = np.random.randint(1,10,(5,5))
arr1,arr2
print("Adiition of two 2D arrays \n",  arr1+arr2)
print("Subtraction of two 2D arrays \n",  arr1-arr2)
print("Multiplication of two 2D arrays \n",  arr1*arr2)
print("Division of two 2D arrays \n",  arr1/arr2)

Adiition of two 2D arrays 
 [[ 9 14  6 16  5]
 [ 7 17 11  8 14]
 [12 12  5 15 17]
 [ 9  8  3 12 10]
 [ 8 11 13 12 11]]
Subtraction of two 2D arrays 
 [[-1 -4 -2 -2  1]
 [ 3 -1 -5 -4 -2]
 [-2  6  1  3 -1]
 [-3  2  1  6 -8]
 [ 0 -7  3 -2  5]]
Multiplication of two 2D arrays 
 [[20 45  8 63  6]
 [10 72 24 12 48]
 [35 27  6 54 72]
 [18 15  2 27  9]
 [16 18 40 35 24]]
Division of two 2D arrays 
 [[0.8        0.55555556 0.5        0.77777778 1.5       ]
 [2.5        0.88888889 0.375      0.33333333 0.75      ]
 [0.71428571 3.         1.5        1.5        0.88888889]
 [0.5        1.66666667 2.         3.         0.11111111]
 [1.         0.22222222 1.6        0.71428571 2.66666667]]


In [28]:
#Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
arr = np.eye(5)
arr
arr1 = np.diagonal(arr)
print("Original array",arr)
print("")
print("Diagnal elements of Original array\n", arr1)


Original array [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagnal elements of Original array
 [1. 1. 1. 1. 1.]


In [39]:
#Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
primes = [num for num in arr if is_prime(num)]

# Print the original array and the prime numbers
print("Original Array:", arr)
print("Prime Numbers:", primes)

Original Array: [ 45  19 959 164 526 166 831 542 654 335 691 882 577 409   5  95 759 550
 600 715 175 383 337 429 547 759 660  70 492 376 741  39 419 251  76 289
 817 615 480 333 466 659 177 402 125 936 677 886 191 905 547  98 454 817
 152 696 858 317 105 521 607  77 996 152 884 108 756 426 887 118 903 609
 217 270 380 470 727 948  60 234 247 326   4 659 292 774 412 588 665 894
 233 205 505 212 400 928  43 596 840 754]
Prime Numbers: [19, 691, 577, 409, 5, 383, 337, 547, 419, 251, 659, 677, 191, 547, 317, 521, 607, 887, 727, 659, 233, 43]


In [43]:
#Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np

# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.uniform(low=10, high=35, size=28)  # temperatures between -10°C and 35°C

# Reshape the array into a 2D array with 4 weeks (each week has 7 days)
weekly_temperatures = daily_temperatures.reshape(4,7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the daily temperatures and weekly averages
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures for the Month: [32.02282374 10.62324548 32.68251388 25.05879457 31.51150446 10.46668488
 12.99395589 22.81035689 23.71667607 28.52629449 14.54953721 25.4932605
 24.30592219 25.82815597 33.77823388 15.09550487 13.87415721 17.95701865
 19.38211493 29.23191775 10.4771207  25.20641078 33.90367904 34.94793849
 16.64281503 11.31429601 13.63524301 25.60045286]
Weekly Averages: [22.19421756 23.60431476 19.97086685 23.0358336 ]
